### <a name='0'></a> Import of libraries

In [1]:
import numpy as np

np.__version__

'1.24.3'

### <a name='1'></a> Exercise 1
Check if all array elements $ A, B, C $ and $ D $ return the logical value _True_.

```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])
```

__Tip:__ Use the function _np.all()_.

In [10]:
# enter solution here
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])

print(np.all(A))
print(np.all(B))
print(np.all(C))
print(np.all(D))

True
False
False
True


### <a name='2'></a> Exercise 2
Check if all array elements $ A, B $ and $ C $ return the logical value _True_ along the axis with index 1.

```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])
```

__Tip:__ Use the function _np.all()_ with the parameter _axis_.

In [5]:
# enter solution here

A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])
np.all(A , 1)

array([ True,  True])

In [6]:
B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])
np.all(B , 1)

array([ True, False])

In [7]:
C = np.array([[True, False, False],
              [True, True, True]])
np.all(C , 1)

array([False,  True])

### <a name='3'></a> Exercise 3
Check if any element of arrays $ A, B, C $ and $ D $ returns the logical value _True_.

```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```

__Tip:__ Use the _np.any()_ function.

In [9]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

result_A = np.any(A)
result_B = np.any(B)
result_C = np.any(C)
result_D = np.any(D)


print(result_A)
print(result_B)
print(result_C)
print(result_D)

False
True
True
True


### <a name='4'></a> Exercise 4
Check if any element of arrays $ A, B, C $ and $ D $ returns the logical value _True_ along the axis with index 0.

```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```

__Tip:__ Use the _np.any()_ function with the parameter _axis_.


In [11]:
# enter solution here
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

result_A = np.any(A , 1)
result_B = np.any(B , 1)
result_C = np.any(C , 1)
result_D = np.any(D , 1)


print(result_A)
print(result_B)
print(result_C)
print(result_D)

[False False]
[False  True]
[False  True]
[ True]


### <a name='5'></a> Exercise 5
Check the array $ A $ for missing data (_np.nan_).

```
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
```
__Tip:__ Use the _np.isnan()_ function.


In [13]:
# enter solution here
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
np.isnan(A)

array([[False, False, False,  True],
       [False,  True, False, False]])

### <a name='6'></a> Exercise 6
Check if the following arrays $ A $ and $ B $ are equal in terms of elements (element-wise) with the specified tolerance level. Use the _np.allclose()_ function with default parameters.

```
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])
```

In [15]:
# enter solution here
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

np.allclose(A, B)

True

### <a name='7'></a> Exercise 7
Check if the following arrays $ A $ and $ B $ are equal in terms of elements (element-wise). Use the comparison operator _==_.

```
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])
```

In [17]:
# enter solution here

A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])

np.all(A == B)


False

### <a name='8'></a> Exercise 8

Check which elements (element-wise) from the array $ A $ below have higher values than the array $ B $.

```
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])
```

In [20]:
# enter solution here

A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

print(np.max(A))
print(np.max(B))

0.9
0.91


### <a name='9'></a> Exercise 9

Create an array of numpy dimensions _4x4_ filled with zeros. Set the data type to _int_.

__Expected result:__

```
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])
```
__Tip:__ Use the _np.zeros()_ function.

In [29]:
# enter solution here

arr = np.zeros((4,4) , dtype = int )
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### <a name='10'></a> Exercise 10
Create an array of numpy dimensions _10x10_ filled with number 255. Set the data type to _float_.

__Expected result:__
```
array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])
```

__Tip:__ Use the _np.ones()_ or _np.full()_ functions.

In [33]:
# enter solution here
arr = np.full((10,10) , 255. , dtype = float )
arr

array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])

### <a name='1'></a> Exercise 11
Build a one-dimensional numpy array of two-digit numbers.

__Expected result:__
```
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])
```

__Tip:__ Use the _np.arange()_ function.


In [34]:
# enter solution here

arr = np.arange(10,100)

### <a name='2'></a> Exercise 12

Build the numpy array specified below:

```
array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
```

Note that the shape of the array is (9, 10).

__Tip:__ Use the _np.arange()_ function and the _np.ndarray.reshape()_ method.



In [38]:
# enter solution here

arr = np.arange(10,100).reshape()
arr

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### Reminder

### Identity matrix:

Identity matrix - a square matrix which coefficients are given by the formula:
$${\displaystyle a_{ij}={\begin{cases}1\quad {\text{dla}}\quad i=j\\[2pt]0\quad {\text{dla}}\quad i\neq j\end{cases}}}$$

#### Examples:
${\displaystyle I_{1}={\begin{bmatrix}1\end{bmatrix}},\;I_{2}={\begin{bmatrix}1&0\\0&1\end{bmatrix}},\;I_{3}={\begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix}}}$

### <a name='3'></a> Exercise 13

Build a _6x6_ two-dimensional array - identity matrix. Use the _int_ data type.

__Expected result:__

```
array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])
```
__Tip:__ Use the _np.eye()_ function.


In [41]:
# enter solution here

np.eye(6,6 , dtype = int )

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

### <a name='4'></a> Exercise 14

Set the random seed to 10. Then build a one-dimensional array consisting of 30 pseudo-randomly generated values from the uniform distribution above the $ [0, 1) $ interval.

__Expected result:__

```
array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578,
       0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317,
       0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895])
```
__Tip:__ Use the function _np.random.rand()_.


In [45]:
# enter solution here

np.random.seed(10)
arr = np.random.rand(30)
arr

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578,
       0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317,
       0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895])

### <a name='5'></a> Exercise 15

Set the random seed to 20. Then build a two-dimensional array with the shape _(10, 4)_ pseudo-random values generated from the standard normal distribution $ N (0, 1) $.

__Expected result:__
```
array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191],
       [-1.08483259,  0.55969629,  0.93946935, -0.97848104],
       [ 0.50309684,  0.40641447,  0.32346101, -0.49341088],
       [-0.79201679, -0.84236793, -1.27950266,  0.24571517],
       [-0.0441948 ,  1.56763255,  1.05110868,  0.40636843],
       [-0.1686461 , -3.18970279,  1.12013226,  1.33277821],
       [-0.24333877, -0.13003071, -0.10901737,  1.55618644],
       [ 0.12877835, -2.06694872, -0.88549315, -1.10457948],
       [ 0.93286635,  2.059838  , -0.93493796, -1.61299022],
       [ 0.52706972, -1.55110074,  0.32961334, -1.13652654]])
```
__Tip:__ Use the function _np.random.randn()_.


In [48]:
# enter solution here
np.random.seed(20)
arr = np.random.randn(10,4)
arr

array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191],
       [-1.08483259,  0.55969629,  0.93946935, -0.97848104],
       [ 0.50309684,  0.40641447,  0.32346101, -0.49341088],
       [-0.79201679, -0.84236793, -1.27950266,  0.24571517],
       [-0.0441948 ,  1.56763255,  1.05110868,  0.40636843],
       [-0.1686461 , -3.18970279,  1.12013226,  1.33277821],
       [-0.24333877, -0.13003071, -0.10901737,  1.55618644],
       [ 0.12877835, -2.06694872, -0.88549315, -1.10457948],
       [ 0.93286635,  2.059838  , -0.93493796, -1.61299022],
       [ 0.52706972, -1.55110074,  0.32961334, -1.13652654]])

### <a name='6'></a> Exercise 16
Set the random seed to 30. Then build a two-dimensional array with the shape _(10, 4)_ pseudo-random values generated from the normal distribution $ N (100, 5) $.
$\mu=100$   
$\sigma^{2}=5$

__Expected result:__
```
array([[ 97.17349231, 103.41650023,  97.82942436, 101.05220329],
       [ 99.7748353 , 100.67930221,  96.14063068, 103.544381  ],
       [100.30029631,  97.52499594, 103.52901961, 100.24037271],
       [ 98.29153712,  98.2666258 , 103.09437633, 101.70027274],
       [ 99.36127721, 101.20382627,  95.34026547, 102.09694365],
       [ 99.98708001,  98.95468525,  99.05410904, 102.38025432],
       [ 93.50787269, 103.61547679, 103.18753701,  98.51356237],
       [102.20256689,  96.19764407,  97.54000366,  97.05813038],
       [101.81233513,  97.66380453,  98.45883627,  98.09317768],
       [102.48979932,  95.70413391,  98.43161651, 101.89861815]])
```
__Tip:__ Use the function _np.random.rand()_.


In [51]:
# enter solution here

np.random.seed(30)

arr = np.random.normal(100, 5, size=(10, 4))

print(arr)

[[ 93.67973668 107.63952676  95.14644531 102.35279808]
 [ 99.49651642 101.51896592  91.37018786 107.92547685]
 [100.67148297  94.46572267 107.89112775 100.53748971]
 [ 96.17976087  96.12405745 106.91923583 103.80192542]
 [ 98.57177243 102.69183738  89.58051684 104.68890855]
 [ 99.97111002  97.66260516  97.8849235  105.32241047]
 [ 85.48316202 108.08445187 107.12754943  96.67622441]
 [104.9250893   91.49767367  94.49928096  93.42177955]
 [104.05250455  94.77610813  96.55385313  95.73621568]
 [105.56736054  90.39415141  96.49298791 104.24543925]]


### <a name='7'></a> Exercise 17
Iterating by array numpy $ A $ element by element (element-wise) print each element of the array to the console.

```
A = np.array([[1, 4, 3],
              [5, 2, 6]])
```

__Tip:__ Use the _np.nditer()_ function.


In [55]:
# enter solution here

A = np.array([[1, 4, 3],
              [5, 2, 6]])
for x in np.nditer(A):
    print(x)

1
4
3
5
2
6


### <a name='8'></a> Exercise 18
Create a one-dimensional numpy array (vector) consisting of 11 equally spaced points from the interval $ [0, 1]. $

__Expected result:__
```
array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])
```
__Tip:__ Use the _np.linspace()_ function.



In [57]:
# enter solution here
arr = np.linspace(0, 1, 11)

print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### <a name='9'></a> Exercise 19

Set the random seed to 42. Generate a one-dimensional array (vector) containing the possible result from the Big Lotto game.

__Expected result:__
```
array([39, 29, 15, 43,  8, 21])
```

__Tip:__ The result of the game is a 6-element vector of values from 1 to 49 inclusive.



In [59]:
# enter solution here
np.random.seed(42)
arr =  np.random.randint(1, 50, 6)
arr

array([39, 29, 15, 43,  8, 21])

### <a name='10'></a> Exercise 20
Build the two-dimensional _6x6_ size array below:

```
array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])
```
__Tip:__ Use the _np.diag()_ function.



In [64]:
# enter solution here

arr = np.diag(range(6))
arr

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

### <a name='1'></a> Exercise 21
Generate the following numpy array. Save the array to a binary file named _'array.npy'_ and then load that file back into another variable.

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```
__Tip:__ Use the _np.save()_ and _np.load()_ functions.


In [67]:

array = np.array([[0, 1, 2, 3],
                           [4, 5, 6, 7],
                           [8, 9, 10, 11]])


np.save('array.npy', array)

load= np.load('array.npy')

print(load)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### <a name='2'></a> Exercise 22
Generate the following numpy array:
```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```

Save the array to a text file named _'array.txt'_ with two decimal places and then load the file back into another variable.

__Tip:__ Use the _np.savetxt()_ and _np.loadtxt()_ functions.


In [72]:
# enter solution here
A = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
np.savetxt( "array.txt", A )
load = np.loadtxt("array.txt")
load

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

### <a name='3'></a> Exercise 23
Generate and convert the following numpy array into a list:

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```
__Tip:__ Use the _np.array.tolist()_ method.


In [76]:
# enter solution here

A = np.array(  [[ 0,  1,  2,  3],
               [ 4,  5,  6,  7],
               [ 8,  9, 10, 11]])
A.tolist()

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]

### <a name='4'></a> Exercise 24
The following numpy array is given:
```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```

Using the cut operator, transform the array into the following:

* swap rows (first with last)

```
array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])
```

In [78]:
# enter solution here

arr = np.array([[ 0,  1,  2,  3],
               [ 4,  5,  6,  7],
               [ 8,  9, 10, 11]])

array =arr[::-1]
print(array)

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


* swap columns (reverse order)

```
array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])
```

In [80]:
# enter solution here
arr = np.array([[ 0,  1,  2,  3],
               [ 4,  5,  6,  7],
               [ 8,  9, 10, 11]])

array =arr[::,::-1]
print(array)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


* swapp rows and columns (reverse order)

```
array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])
``` 

In [81]:
# enter solution here

arr = np.array([[ 0,  1,  2,  3],
               [ 4,  5,  6,  7],
               [ 8,  9, 10, 11]])

array =arr[::-1,::-1]
print(array)

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


### <a name='5'></a> Exercise 25
The following numpy array:

```
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
```
Transform to array:

```
array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])
```

__Tip:__ Use the _np.pad()_ function.

In [86]:
# enter solution here

A = np.array([[1., 1., 1., 1.],
             [1., 1., 1., 1.],
             [1., 1., 1., 1.],
             [1., 1., 1., 1.]])

np.pad(A,1)


array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

### <a name='6'></a> Exercise 26
The following numpy array:
```
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])
```

Transform to array:
```
array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])
```

__Tip:__ Use the cut operator and assign the appropriate values.


In [88]:
# enter solution here

arr = np.array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])


arr[::2, ::2] = 10
arr[1::2, ::2] = 5

print(arr)

[[10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]]


### <a name='7'></a> Exercise 27
Combine the following arrays: $ A $ and $ B $ into one array.

```
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
```

__The expected result:__

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])
```

__Tip:__ Use the _np.append()_ function.


In [92]:
# enter solution here
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])

np.append(A,B , axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])

### <a name='8'></a> Exercise 28
Use the $ A $ and $ B $ arrays below to extract the common elements (intersection) of the arrays.

```
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])      
```
__Tip:__ Use the _np.intersect1d()_ function.

In [95]:
# enter solution here

A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])  


np.intersect1d(A, B)

array([0, 2, 3])

### <a name='9'></a> Exercise 29
The following numpy array $ A $ is given.
Find the unique values of this array.

```
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])
```

__Tip:__ Use the _np.unique()_ function.

In [96]:
# enter solution here
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])
np.unique(A)

array([1, 2, 4, 5, 7, 9])

### <a name='10'></a> Exercise 30
The array below is given:
```
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
```
Return indexes with maximum values for a given row.

__Tip:__ Use the _np.argmax()_ function.

In [98]:
# enter solution here

A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])

np.argmax(A)

5

### <a name='1'></a> Exercise 31
Sort the array $ A $ below:
* by row (ascending)
* by column (ascending)

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```
__Tip:__ Use the _np.sort()_ function.


In [100]:
# enter solution here

A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
np.sort(A,axis = 0) 

array([[ 1.99,  2.39,  4.99],
       [ 4.99,  3.49,  7.29],
       [14.99,  9.99,  9.99]])

### <a name='2'></a> Exercise 32
Extract all elements of the $ A $ array with a value greater than 8.
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```

In [101]:
# enter solution here


A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
A[A > 8]

array([ 9.99,  9.99, 14.99])

### <a name='3'></a> Exercise 33
The following array $ A $ is given. Replace elements above 10 with a fixed value of 10 (truncation to 10).

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Tip:__ Use the _np.where()_ function.


In [103]:
# enter solution here

A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

np.where(A>10,10,A)

array([[ 4.99,  3.49,  9.99],
       [ 1.99,  9.99, 10.  ],
       [10.  ,  2.39,  7.29]])

### <a name='4'></a> Exercise 34
Present the following $ A $ two-dimensional array as a "flattened" one-dimensional array.
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Expected result:__
```
array([ 4.99,  3.49,  9.99,  1.99,  9.99, 14.99, 14.99,  2.39,  7.29])
```

__Tip:__ Use the _np.ravel()_ function.

In [104]:
# enter solution here

A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])


np.ravel(A)

array([ 4.99,  3.49,  9.99,  1.99,  9.99, 14.99, 14.99,  2.39,  7.29])

### <a name='5'></a> Exercise 35
Build an array of the same shape and data type as the $ A $ array and fill it with a constant value of 0.0.

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Expected result:__
```
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
```

__Tip:__ Use the _np.zeros_like()_ function.

In [105]:
# enter solution here

A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

np.zeros_like(A)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### <a name='6'></a> Exercise 36

Build an array of the same shape and data type as the $ A $ array and fill it with a constant value of 9.99.

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Expected result:__

```
array([[9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99]])
```

__Tip:__ Use the function _np.full_like()_.




In [106]:
# enter solution here

A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

np.full_like(A , 9.99)

array([[9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99]])

### <a name='7'></a> Exercise 37
Build a two-dimensional array (lower triangular matrix) below:
```
array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])
```
__Tip:__ Use the _np.tri()_ function.

In [111]:
# enter solution here

A = np.array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

np.tri(5, 5, 0)


array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

### <a name='8'></a> Exercise 38
Create any $ (2, 3, 4) $ 3-dimensional array.

In [113]:
# enter solution herearr = np.zeros((2,3,4))

arr = np.arange(24).reshape(2,3,4)
arr


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### <a name='1'></a> Exercise 41
The following array $ A $ with the shape (2, 3) is given.
```
A = np.array([[4, 2, 1],
              [6, 4, 2]])
```

In [119]:
# enter solution here

A = np.array([[4, 2, 1],
              [6, 4, 2]])
B = np.expand_dims(A, axis = 0)

print(B.shape)

(1, 2, 3)


* Expand the array $ A $ by one dimension (add a new dimension at the beginning). Expected shape of the output array: _(1, 2, 3)_.

__Tip:__ Use the _np.expand_dims()_ function.

In [ ]:
# enter solution here

In [121]:
A = np.array([[4, 2, 1],
              [6, 4, 2]])
B = np.expand_dims(A, axis = -1)

print(B.shape)

(2, 3, 1)


* Expand the array $ A $ by one dimension (add a new dimension at the end). Expected shape of the output array: _(2, 3, 1)_.

__Tip:__ Use the _np.expand_dims()_ function.

### <a name='2'></a> Exercise 42
Generate a three-dimensional array named _image_ with shape _(200, 300, 3)_ filled with random values from 0 to 255 inclusive and data type _np.uint8_.

In [126]:
# enter solution here
image = np.random.randint(0, 256, size = (200, 300, 3), dtype=np.uint8)

print(image.shape)


(200, 300, 3)


Then run the following block of code. As a result, you'll get a preview of a randomly generated color image.

In [127]:
# enter solution here
print(image)

[[[185 210 156]
  [ 88 232  85]
  [ 55  38  23]
  ...
  [246 244 247]
  [ 67 209 112]
  [104  53 174]]

 [[ 47 183 238]
  [199 107  86]
  [ 97 197 221]
  ...
  [ 17  13  43]
  [144 189 206]
  [  5 174 221]]

 [[183  29  46]
  [ 36 228 127]
  [  3  53 151]
  ...
  [114  60 144]
  [141  95 172]
  [230 227  51]]

 ...

 [[240 101  74]
  [214 162 201]
  [142 128  29]
  ...
  [ 41 188  85]
  [198 230  44]
  [ 58  59 204]]

 [[ 45  83  19]
  [204  23  51]
  [199 208  76]
  ...
  [ 49  95 111]
  [175 141  10]
  [139  58 163]]

 [[ 56  18 209]
  [ 37 213  67]
  [106  50  49]
  ...
  [199  40 196]
  [141   8  82]
  [ 23 106 192]]]


### <a name='8'></a> Exercise 48
The following array $ A $ with the shape _(1, 2, 3)_ is given.

```
A = np.array([[[1, 2, 3],
               [6, 3, 2]]])
```

Remove the unnecessary first dimension and get an array of _(2, 3)_.

__Tip:__ Use the _np.squeeze()_ function.


In [128]:
# enter solution here
A = np.array([[[1, 2, 3],
               [6, 3, 2]]])
np.squeeze()

array([[1, 2, 3],
       [6, 3, 2]])

### <a name='9'></a> Exercise 49
The following array $ A $ with the shape _(4, 1)_ is given.
```
A = np.array([[0.4],
              [0.9],
              [0.5],
              [0.6]])
```
Remove the unnecessary dimension and get an array with the shape _(4,)_.

__Tip:__ Use the _np.squeeze()_ function.

In [129]:
# enter solution here

A = np.array([[0.4],
              [0.9],
              [0.5],
              [0.6]])

np.squeeze(A)

array([0.4, 0.9, 0.5, 0.6])

### <a name='10'></a> Exercise 50
The first image was extract from the _images_ array as follows:

In [132]:
image1 = image[:1]
image1.shape

(1, 300, 3)

Using the knowledge from previous exercises, remove the unnecessary first dimension of the _image1_ array.

In [ ]:
# enter solution here

# <a name='1'></a> Exercise 51
Two arrays $ A $ and $ B $ are given below:

```
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
```
* Concatenate these arrays as follows:

```
array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])
```

__Tip:__ Use the _np.concatenate()_ function.

In [137]:
# enter solution here
A = np.array([[3, 4, 5], 
              [8, 3, 1]])

B = np.array([[0, 5, 2],
              [4, 2, 1]])

C = np.concatenate((A, B))

print(C)

[[3 4 5]
 [8 3 1]
 [0 5 2]
 [4 2 1]]


In [ ]:
# enter solution here

### <a name='2'></a> Exercise 52
The first array is given containing the data (_data_) and the second array containing the target class (_target_) for the given row:

```
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
```

Concatenate these arrays into one as shown below:

```
array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])
```

In [5]:
# enter solution here

data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])

A = np.concatenate((data,target) , axis = 1)

A


array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

### <a name='3'></a> Exercise 53
The following three one-dimensional arrays are given:
```
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
```
Transform each of these arrays into a column and concatenate them into one large array.

__Expected result:__
```
array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])
```
__Tip:__ Use the function _np.column_stack()_.


In [10]:
# enter solution here

feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])

C = np.column_stack((feature1 ,feature2,feature3))
C

array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])

### <a name='4'></a> Exercise 54
The following two-dimensional array is given:
```
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A
```
```
array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])
```
Split an array into three parts so that the first two columns formed the first array $ A1 $, four consecutive second array $ A2 $ and the last two third array $ A3 $.

__Tip:__ Use the function _np.split()_.

In [20]:
# enter solution here


A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A

A1, B, C = np.split(A, [2, 6], axis=1)

print(A)
print(B)
print(C)

[[0 0 3 5 2 3 1 1]
 [0 0 2 6 2 6 1 1]
 [0 0 2 4 4 1 1 1]
 [0 0 3 4 5 1 1 1]
 [0 0 5 3 4 4 1 1]]
[[3 5 2 3]
 [2 6 2 6]
 [2 4 4 1]
 [3 4 5 1]
 [5 3 4 4]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


### <a name='5'></a> Exercise 55
The following numpy array $ A $ is given:

```
A = np.random.randint(low=0, high=2, size=(10, 6))
```

Calculate the total number of non-zero elements for this array.

__Tip:__ Use the function _np.count_nonzero()_.


In [22]:
# enter solution here

A = np.random.randint(low=0, high=2, size=(10, 6))

np.count_nonzero(A)


23

Calculate the total number of non-zero elements for each row in this array.

__Tip:__ Use the function _np.count_nonzero()_.

In [27]:
# enter solution here
A = np.random.randint(low=0, high=2, size=(10, 6))

np.count_nonzero(A,axis = 1)

array([2, 0, 4, 4, 4, 4, 3, 2, 3, 2], dtype=int64)

### <a name='6'></a> Exercise 56
An example numpy array $ A $ is given below:

```
A = np.random.randn(10, 4)
```

```
array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])
```

Set the numpy library option to print arrays with specified precision. Set its value to 4 and print the $ A $ array.

In [3]:
# enter solution here

np.set_printoptions(precision=4) 

A = np.random.randn(10, 4)

print(A)

[[ 0.468  -0.4452  1.1122 -1.7849]
 [-0.3191  0.4285 -0.3043  0.5014]
 [ 1.2362 -0.9141 -1.3908  0.1626]
 [-0.5005 -0.6726 -1.6002  1.098 ]
 [-0.7206 -0.375   0.255  -0.5053]
 [-0.1496  2.1418  0.8038 -1.2003]
 [-0.0723 -0.7629  0.5068  0.1482]
 [-0.7523 -0.6472 -0.2278  0.5814]
 [ 0.8019 -0.4685 -1.0113 -0.3371]
 [-0.2846 -0.5287 -0.3984  0.9396]]


### <a name='7'></a> Exercise 57

The following numpy array $ A $ is given:

```
A = np.array([1.2e-6, 1.7e-7])
```
Set the precision value to 8. Then set the appropriate numpy library option to suppress mathematical notation. Print the array $ A $.

__Expected result:__
```
array([0.0000012 , 0.00000017])
```


In [28]:
# enter solution here

A = np.array([1.2e-6, 1.7e-7])

np.set_printoptions(precision=8, suppress=True)
print(A)

[0.0000012  0.00000017]


### <a name='8'></a> Exercise 58
The following numpy array $ A $ is given:
```
A = np.random.randn(8, 4)
```
Remove the third column from the $ A $ array.

__Expected result:__
```
array([[-0.55692881, -0.66003196,  0.70856031],
       [ 0.22378737, -0.19796576, -0.16889332],
       [ 0.26062786,  0.29865445, -0.92259267],
       [-2.40317659,  1.79961876, -1.96495796],
       [ 0.13051561, -1.7085185 ,  0.54885043],
       [ 1.77268727,  0.38751181, -0.05141955],
       [-1.80858596, -0.45075211,  0.15332866],
       [ 1.94218961, -1.93679529, -1.83350954]])
```
__Tip:__ Use the _np.delete()_ function.


In [29]:
# enter solution here

A = np.random.randn(8, 4)

A = np.delete(A, 2, axis=1) 

print(A)

[[-0.59612413 -0.45223766 -0.61017951]
 [ 0.50419865  0.89236913  0.3855247 ]
 [ 0.29124492  2.08800999 -0.1189532 ]
 [-1.82453602  1.02646322  0.02784579]
 [-0.29193204  0.77958308 -0.31936087]
 [-0.78278532 -1.84924162  1.82986262]
 [-0.55603663  0.08537067  0.39288196]
 [-0.7796178  -0.76445426 -0.60853813]]


### <a name='9'></a> Exercise 59

A one-dimensional array $ v $ (vector) is given:

```
v = np.array([3, 4, -2])
```
Calculate the norm of the vetor $ v $.


In [30]:
# enter solution here

v = np.array([3, 4, -2])

norm = np.linalg.norm(v)

print(norm)

5.385164807134504


### <a name='10'></a> Exercise 60
An example $ A $ array is given below:

```
A = np.random.randint(10, size=(100, 30))
```
Set the numpy library option to print 10 edge elements. Print the array $ A $.


In [31]:
# enter solution here

A = np.random.randint(10, size=(100, 30))

np.set_printoptions(edgeitems=10)
print(A)

[[2 4 8 0 8 4 3 5 9 5 ... 9 9 9 4 0 3 0 8 9 8]
 [7 4 0 7 1 8 7 9 8 8 ... 5 6 7 6 9 3 2 9 1 1]
 [3 1 0 0 6 1 9 3 0 9 ... 4 3 3 0 4 4 6 6 9 2]
 [2 9 5 9 5 5 2 8 2 7 ... 6 1 3 3 6 7 7 4 1 5]
 [8 2 1 2 5 8 7 9 5 6 ... 8 3 1 8 6 0 2 9 0 3]
 [7 6 7 4 6 4 1 3 8 7 ... 7 0 3 2 5 9 7 7 3 0]
 [9 6 0 8 3 3 9 3 5 0 ... 6 7 9 1 8 1 3 3 8 4]
 [8 6 1 1 9 1 5 1 1 4 ... 1 5 1 7 5 8 8 2 3 9]
 [7 7 3 3 8 6 8 8 5 4 ... 5 0 5 1 1 6 5 5 7 3]
 [0 7 0 7 8 5 9 1 3 2 ... 2 6 8 3 5 0 5 9 4 3]
 ...
 [3 1 7 7 3 3 1 0 2 6 ... 1 5 4 0 6 5 1 9 7 4]
 [8 7 1 1 0 3 7 7 5 7 ... 4 5 0 9 3 2 6 0 0 9]
 [9 5 8 9 3 2 8 4 3 0 ... 0 0 2 8 0 0 9 1 8 3]
 [9 4 9 7 4 5 3 5 2 0 ... 0 1 9 2 7 3 1 8 0 5]
 [8 2 3 2 3 2 3 2 0 3 ... 6 3 1 7 0 4 8 2 2 0]
 [8 8 6 0 3 5 8 1 1 1 ... 6 1 0 9 7 1 9 8 5 9]
 [9 1 2 6 4 1 3 4 2 3 ... 0 7 5 6 9 9 1 7 9 9]
 [4 6 4 4 2 3 1 6 8 3 ... 7 4 3 0 8 1 4 3 7 2]
 [2 1 3 2 9 0 3 0 0 2 ... 3 3 1 1 9 4 5 4 8 0]
 [8 3 9 8 8 3 9 4 8 6 ... 1 5 5 6 8 5 7 0 4 3]]


### <a name='1'></a> Exercise 61
The following two arrays $ A $ and $ B $ are given:

```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
```

Determine an array consisting of arithmetic means $ A $ and $ B $ of the corresponding elements.

__Expected result:__
```
array([[3.5, 3.5, 5.5, 3.5],
       [5.5, 3. , 1.5, 5.5]])
```

In [32]:
# enter solution here

A = np.array([[3, 4, 9, 2], 
              [5, 3, 2, 5]])

B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

C = (A + B) / 2

print(C)

[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]]


### <a name='2'></a> Exercise 62
The following two arrays $ A $ and $ B $ are given:
```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
```
Multiply arrays element-by-element (element-wise).

In [33]:
# enter solution here

A = np.array([[3, 4, 9, 2], 
              [5, 3, 2, 5]]) 

B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

C = A * B

print(C)

[[12 12 18 10]
 [30  9  2 30]]


### <a name='3'></a> Exercise 63
The following numpy array $ A $ is given:
```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
```
Determine the root of each element of the array $ A $.

__Tip:__ Use the _np.sqrt()_ function.

In [35]:
# enter solution here

A = np.array([[3, 4, 9, 2], 
              [5, 3, 2, 5]])

B = np.sqrt(A)

print(B)

[[1.73205081 2.         3.         1.41421356]
 [2.23606798 1.73205081 1.41421356 2.23606798]]


### <a name='4'></a> Exercise 64
The following arrays $ A $ and $ B $ are given:
```
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')
```
Check the Pythagorean formula for sines and cosines on the $ A $ array and then compare the result with the $ B $ array. Use the _np.allclose()_ function.

__Pythagorean formula for sines and cosines:__ For any angle value $\alpha \in R $:
$$sin^2\alpha + cos^2\alpha = 1$$

In [4]:
# enter solution here


A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')

sin_A = np.sin(A)
cos_A = np.cos(A)

identity_holds = np.allclose(sin_A**2 + cos_A**2, B)

print(identity_holds)

True


### Reminder
### Matrix mulitplication:
$${A} ={\begin{bmatrix}a_{11}&a_{12}&\cdots &a_{1n}\\a_{21}&a_{22}&\cdots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\cdots &a_{mn}\\\end{bmatrix}}$$
A - $m\ x\ n$ matrix

$$ {B} ={\begin{bmatrix}b_{11}&b_{12}&\cdots &b_{1p}\\b_{21}&b_{22}&\cdots &b_{2p}\\\vdots &\vdots &\ddots &\vdots \\b_{n1}&b_{n2}&\cdots &b_{np}\\\end{bmatrix}}$$
B - $n\ x\ p$ matrix

$$C = AB$$
C - $ m \ x \ p $ matrix  
To be able to multiply two matrices, the number of columns in the left matrix must match the number of rows in the right matrix.

Matrix multiplication is not alternating! $$AB \neq BA$$

### Example 1
$ X = \begin{bmatrix}5&3\\3&9\end{bmatrix}$, $ Y= \begin{bmatrix}1\\-1\end{bmatrix} $   
$ X - $ 2x2 matrix  
$ Y - $ 2x1 matrix  
$$Z = X \cdot Y = \begin{bmatrix}5&3\\3&9\end{bmatrix} \cdot \begin{bmatrix}1\\-1\end{bmatrix} = \begin{bmatrix}2\\-6\end{bmatrix}$$
$ Z - $ 2x1 matrix  

### Example 2
$X = \begin{bmatrix}2&-1&3\\3&1&0\end{bmatrix}$, $Y = \begin{bmatrix}2&1&-1\\0&-1&2\\3&2&0\end{bmatrix}$    
  
$X  -$ 2x3 matrix     
$Y - $ 3x3 matrix  
$$Z = X \cdot Y =  \begin{bmatrix}2&-1&3\\3&1&0\end{bmatrix} \cdot \begin{bmatrix}2&1&-1\\0&-1&2\\3&2&0\end{bmatrix} = \begin{bmatrix}13&9&-4\\6&2&-1\end{bmatrix}$$
$Z - $ 2x3 matrix  

### <a name='5'></a> Exercise 65
Two two-dimensional arrays are provided, numpy $ A $ and $ B $.  
$ A $ - dimension matrix $ (3, 2) $  
$ B $ - dimension matrix $ (2, 3) $  
```
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])
```
Perform matrix multiplication of $ A $ and $ B $ arrays.

__Tip:__ Use the _np.dot()_ function.

In [37]:
# enter solution here

import numpy as np

A = np.array([[2, 3], 
              [-4, 2],
              [5, 0]])

B = np.array([[4, 3, 2],
              [-1, 0, 2]])

C = np.dot(A, B)

print(C)

[[  5   6  10]
 [-18 -12  -4]
 [ 20  15  10]]


### Reminder

### Determinant of the matrix:

$${\displaystyle A={\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{bmatrix}}}$$
$A$ - _nxn_ matrix

#### Signs:

${\displaystyle |A|=\left|{\begin{array}{c}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{array}}\right|} $  lub  $ {\displaystyle \det A=\det {\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{bmatrix}}}$

#### Example:
${\displaystyle \det A={\begin{vmatrix}a_{11}&a_{12}\\a_{21}&a_{22}\end{vmatrix}}=a_{11}a_{22}-a_{12}a_{21}}$

${\displaystyle \det A={\begin{vmatrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\end{vmatrix}}=a_{11}a_{22}a_{33}+a_{21}a_{32}a_{13}+a_{31}a_{12}a_{23}-a_{21}a_{12}a_{33}-a_{11}a_{32}a_{23}-a_{31}a_{22}a_{13}}$

${\displaystyle \det A={\begin{vmatrix}2&4\\-1&3\end{vmatrix}}=2\cdot3-4\cdot(-1)} = 6 + 4 = 10 $

### <a name='6'></a> Exercise 66
The following array (square matrix) $ A $ is given:

```
A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])
```
Compute the determinant of the $ A $ matrix.

__Tip:__ Use the function _np.linalg.det()_.


In [38]:
# enter solution here

A = np.array([[-2, 0, 4], 
              [5, 2, -1],
              [-4, 2, 4]])

det_A = np.linalg.det(A)

print(det_A)

51.999999999999986


### <a name='7'></a> Exercise 67
The following array (square matrix) $ A $ is given:
```
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
```
Calculate eigenvalues and their corresponding eigenvectors of the $ A $ matrix.
__Tip:__ Use the function _np.linalg.eig()_.

In [39]:
# enter solution here

A = np.array([[5, 8, 16],  
              [4, 1, 8],
              [-4, 4, -11]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [-9.24621125 -3.          7.24621125]
Eigenvectors: [[-0.62616472 -0.89442719  0.89015941]
 [-0.31308236 -0.          0.4450797 ]
 [ 0.71407086  0.4472136  -0.09757197]]


### Reminder
### Inverse matrix:

$ A $ - square matrix of degree $ n $. The $ A $ matrix has an inverse matrix when there is a $ B $ matrix such as
$$ AB = BA = I $$

$A = \begin{bmatrix}2&4\\-1&3\end{bmatrix}$

### <a name='8'></a> Exercise 68
The following array (square matrix) $ A $ is given:
```
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
```
Find the inverse matrix to the $ A $ matrix.

__Tip:__ Use the function _np.linalg.inv()_.

In [5]:
# enter solution here

A = np.array([[5, 8, 16],  
              [4, 1, 8],
              [-4, 4, -11]])

A_inv = np.linalg.inv(A)

print(A_inv)

[[-0.2139  0.7562  0.2388]
 [ 0.0597  0.0448  0.1194]
 [ 0.0995 -0.2587 -0.1343]]


### Reminder

### Matrix trace:

$${\displaystyle A={\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{bmatrix}}}$$
$A$ - nxn matrix

${\displaystyle \operatorname {tr} (A)=\sum _{i=1}^{n}a_{ii}=a_{11}+a_{22}+\dots +a_{nn}}$


#### Example:
$A = \begin{bmatrix}2&4\\-1&3\end{bmatrix}$

${\displaystyle \operatorname {tr} (A)=\sum _{i=1}^{2}a_{ii}=a_{11}+a_{22} = 2 + 3 = 5}$

### <a name='9'></a> Exercise 69
The following array (square matrix) $ A $ is given:
```
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
```
Find the trace of the square matrix $ A $ (sum of elements on the main diagonal).

__Tip:__ Use the _np.trace()_ function.

In [42]:
# enter solution here

A = np.array([[5, 8, 16], 
              [4, 1, 8], 
              [-4, 4, -11]])

trace_A = np.trace(A)

print(trace_A)

-5


### Reminder
### Transposed matrix:

Replace rows with columns and columns with rows.

#### Example 1:

$A = \begin{bmatrix}2&4\\-1&3\end{bmatrix}$,
$A^{T} = \begin{bmatrix}2&-1\\4&3\end{bmatrix}$

#### Example 2:
$A = \begin{bmatrix}2&1&-1\\0&-1&2\end{bmatrix}$,
$A^{T} = \begin{bmatrix}2&0\\1&-1\\-1&2\end{bmatrix}$

### Exercise 69 continued
Transpose the $ A $ matrix.

In [9]:
# enter solution here

A = np.array([[2, 3],
              [4, 6],
              [7, 8]])

b = A.T
print(b)


[[2 4 7]
 [3 6 8]]


### <a name='10'> </a> Exercise 70
Two two-dimensional arrays numpy $ A $ and $ B $ are given:  
$ A $ - matrix of $ (4, 2) $ dimension  
$ B $ - matrix of $ (1, 8) $ dimension

```
A = np.array([[2, 0],
              [4, 2],
              [5, 3],
              [4, 2]])
B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])
```
Transform the $ B $ array so that you can do the matrix multiplication of $ A \cdot B $. Perform this multiplication.

__Expected result:__
```
array([[ 8,  0,  4,  2],
       [18,  0, 12, 22],
       [23,  0, 16, 32],
       [18,  0, 12, 22]])
```

### <a name='1'></a> Exercise 71
The following $ A $ array is given:
```
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
```
From the second row of the $ A $ array, randomly shuffle the rows in the array.

__Tip:__ Use the _np.random.shuffle()_ function.


In [22]:
# enter solution here

A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])

np.random.shuffle(A[1:])
print(A)

[['id' 'price']
 ['004' '2.49']
 ['005' '1.49']
 ['003' '7.99']
 ['002' '4.99']
 ['001' '14.99']]


### <a name='2'></a> Exercise 72
The following array $ A $ is given:

```
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
```
Return an array of indexes that will sort the array $ A $ in ascending order.

__Expected result:__

```
array([5, 2, 1, 0, 4, 3])
```
__Tip:__ Use the _np.argsort()_ function.


In [23]:
# enter solution here

A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
np.argsort(A) 

array([5, 2, 1, 0, 4, 3], dtype=int64)

### <a name='3'></a> Exercise 73

The following array $ A $ is given:
```
A = np.random.randn(10, 8)
```
Round the values of this array to three decimal places.

__Tip:__ Use the function _np.round()_.


In [26]:
# enter solution here

A = np.random.randn(10, 8)

np.round(A, 3)

array([[-0.33 , -0.004, -0.998, -0.634, -0.72 , -3.869,  1.983, -0.072],
       [ 1.267,  1.082,  0.634, -0.669,  0.714, -0.674, -1.082,  1.29 ],
       [-0.261, -0.897,  1.433,  0.149,  1.955, -0.373, -0.772, -0.493],
       [ 0.247,  0.32 ,  2.113,  0.327,  0.129,  0.721,  1.937,  0.485],
       [ 0.366,  0.493, -0.19 , -0.363,  1.978, -1.545,  0.316,  0.566],
       [-0.665, -0.911, -0.656,  2.48 ,  0.727,  0.512,  2.019,  0.588],
       [ 0.831,  1.221,  0.072,  0.291,  0.068, -0.436, -0.154,  1.063],
       [ 0.952,  0.347,  0.77 ,  0.469,  0.026, -0.946,  0.599, -0.654],
       [-1.329, -0.115, -0.381, -0.203, -0.079,  0.156,  0.187,  1.018],
       [-1.463,  0.718,  0.441,  0.754,  0.365,  1.893, -0.653, -2.737]])

### <a name='4'></a> Exercise 74
Determine the roots of the polynomial:
* $W(x) = 4x^2 + 5x + 1$

Check the solution.

__Tip:__ Use the _np.roots()_ and _np.polyval()_ functions.

In [2]:
# enter solution here
p = np.poly1d([4, 5, 1])
roots = np.roots(p)
print(roots)
eval_p = np.polyval(p, roots)
print(eval_p)

[-1.   -0.25]
[0. 0.]


### <a name='5'></a> Exercise 75
Determine the roots of polynomials:
* $Q(x) = 2x^3 + 4x^2 -5x + 1$
* $R(x) = 2x^3 -5x + 1$

__Tip:__ Use the _np.roots()_ function.


In [37]:
# enter solution here

p = np.poly1d([2, 0, 4, -5, 1]) 
q = np.poly1d([2, 0, 0, -5, 1])
print(np.roots(p))
print(np.roots(q))

[-0.4849+1.5887j -0.4849-1.5887j  0.717 +0.j      0.2527+0.j    ]
[-0.7416+1.1802j -0.7416-1.1802j  1.2826+0.j      0.2006+0.j    ]


### <a name='6'></a> Exercise 76
Polynomials are given:
* $W(x) = 4x^2 + 5x + 1$
* $Q(x) = 2x^3 + 4x^2 -5x + 1$


In [7]:
# enter solution here

W = np.poly1d([4, 5, 1])

Q = np.poly1d([2, 4, -5, 1])





   3     2
2 x + 8 x + 2


Perform:
* $ W (x) + Q (x) $

In [ ]:
# enter solution here

print(W+Q)

* $W(x) - Q(x)$


In [ ]:
# enter solution here

print(W-Q) 



* $W(x) * Q(x)$


In [ ]:
# enter solution here

print(W*Q)  



* $W(x) + 2Q(x)$

In [8]:
# enter solution here
print(W + 2*Q)

   3      2
4 x + 12 x - 5 x + 3


### <a name='7'></a> Exercise 77
The array below is given:

```
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
```
Use the sign function for the array $ A $. As a reminder, the function works as follows: returns -1 for negative values, zero for zero, and 1 for positive values.

__Expected result:__

```
array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])
```
__Tip:__ Use the _np.sign()_ function.

In [9]:
# enter solution here
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
np.sign(A)

array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])

### <a name='8'></a> Exercise 78
Using the _np.arange()_ function, generate the following array:

```
array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')
```


In [11]:
# enter solution here

dates = np.arange('2021-01-01', '2021-02-01', dtype='datetime64[D]')
print(dates)

['2021-01-01' '2021-01-02' '2021-01-03' '2021-01-04' '2021-01-05'
 '2021-01-06' '2021-01-07' '2021-01-08' '2021-01-09' '2021-01-10'
 '2021-01-11' '2021-01-12' '2021-01-13' '2021-01-14' '2021-01-15'
 '2021-01-16' '2021-01-17' '2021-01-18' '2021-01-19' '2021-01-20'
 '2021-01-21' '2021-01-22' '2021-01-23' '2021-01-24' '2021-01-25'
 '2021-01-26' '2021-01-27' '2021-01-28' '2021-01-29' '2021-01-30'
 '2021-01-31']


### <a name='9'></a> Exercise 79

Using the _np.arange()_ function, generate the following array:

```
array([['2021-01', '2021-02', '2021-03'],
       ['2021-04', '2021-05', '2021-06'],
       ['2021-07', '2021-08', '2021-09'],
       ['2021-10', '2021-11', '2021-12']], dtype='datetime64[M]')
```


In [14]:
# enter solution here

dates = np.arange('2021-01', '2022-01', dtype='datetime64[M]')
print(dates)

['2021-01' '2021-02' '2021-03' '2021-04' '2021-05' '2021-06' '2021-07'
 '2021-08' '2021-09' '2021-10' '2021-11' '2021-12']


### <a name='10'></a> Exercise 80
Using the _np.datetime64()_ function, generate today's date (the date you were doing the exercise).

In [15]:
# enter solution here
today = np.datetime64('today', 'D') 
print(today)

2024-02-03


### <a name='1'></a> Exercise 81
Generate all dates for mondays from January and February 2020 as a numpy array.

__Expected result:__
```
array(['2020-01-06', '2020-01-13', '2020-01-20', '2020-01-27', '2020-02-03', '2020-02-10',
       '2020-02-17', '2020-02-24'], dtype='datetime64[D]')
```

In [22]:
# enter solution here
dates = np.arange('2020-01-01', '2020-03-01', dtype='datetime64[W]', )
print(dates)

['2019-12-26' '2020-01-02' '2020-01-09' '2020-01-16' '2020-01-23'
 '2020-01-30' '2020-02-06' '2020-02-13' '2020-02-20']


### <a name='2'></a> Exercise 82 
Two $ A $ and $ B $ arrays are given:
```
A = np.array(['001', '002', '003'], dtype=np.str)
B = np.array(['XC', 'YC', 'ZC'], dtype=np.str)
```
Merge them together as shown below:

```
array(['001XC', '002YC', '003ZC'], dtype='<U5')
```

__Tip:__ Use the function _np.char.add()_.

In [23]:
# enter solution here

A = np.array(['001', '002', '003'], dtype=np.str_) 
B = np.array(['XC', 'YC', 'ZC'], dtype=np.str_)
result = np.char.add(A, B)
print(result)

['001XC' '002YC' '003ZC']


### <a name='3'></a> Exercise 83
The array below is given:

```
A = np.array(['1', '2', '3'], dtype=np.str)
```
Add '000' (3 zeros) to the beginning of each element of the array.

__Tip:__ Use the function _np.char.add()_ or _np.char.rjust()_ or _np.char.zfill()_.


In [31]:
# enter solution here

A = np.array(['1', '2', '3'], dtype=np.str_) 
B = np.char.add("000", A)
print(B)

['0001' '0002' '0003']


### <a name='4'></a> Exercise 84
The array below is given:
```
A = np.array([['PLW CDR 11B TEN', 'AMC LPP'],
              ['CDR PKO KGH', 'CCC QMK']], dtype=np.str)
```
Split each element of the above array by spaces, obtaining a list of values in each place.

__Expected result:__
```
array([[list(['PLW', 'CDR', '11B', 'TEN']), list(['AMC', 'LPP'])],
       [list(['CDR', 'PKO', 'KGH']), list(['CCC', 'QMK'])]], dtype=object)
```
__Tip:__ Use the function _np.char.split()_.


In [33]:
# enter solution here

A = np.array([['PLW CDR 11B TEN', 'AMC LPP'],
              ['CDR PKO KGH', 'CCC QMK']], dtype=np.str_)

np.char.split(A)

array([[list(['PLW', 'CDR', '11B', 'TEN']), list(['AMC', 'LPP'])],
       [list(['CDR', 'PKO', 'KGH']), list(['CCC', 'QMK'])]], dtype=object)

### <a name='5'></a> Exercise 85
The array below is given:
```
A = np.array([['#summer#time#mood'],
              ['#sport#time']])
```
Replace all # with spaces and then remove any unnecessary spaces around the text.

__Expected result:__
```
array([['summer time mood'],
       ['sport time']], dtype='<U17')
```


In [37]:
# enter solution here

A = np.array([['#summer#time#mood'],
              ['#sport#time']])
np.char.replace(A , "#" , " ")

array([['summertimemood'],
       ['sporttime']], dtype='<U14')

### <a name='6'></a> Exercise 86
The following array is provided:

```
A = np.array([['#summer#time#mood', '#vibe'],
              ['#sport#time', '#good#time'],
              ['#event#summer', '#fast#move']])
```
Count the number of occurrences of the word 'time' in each element of the $ A $ array.

__Tip:__ Use the _np.char.count()_ function.



In [38]:
# enter solution here

A = np.array([['#summer#time#mood', '#vibe'],
              ['#sport#time', '#good#time'],
              ['#event#summer', '#fast#move']])

np.char.count(A,"time")

array([[1, 0],
       [1, 1],
       [0, 0]])

### <a name='7'></a> Exercise 87
The following text is provided containing data (companies from the WIG20 index):

```
text = """ALIOR	PLALIOR00045	88 860 000	1 386 216 000	0,891	2,16	14
CCC	PLCCC0000016	27 918 000	1 292 603 400	0,831	5,28	42
CDPROJEKT	PLOPTTC00011	67 348 000	22 864 646 000	14,702	7,39	7
CYFRPLSAT	PLCFRPT00013	275 301 000	6 854 994 900	4,408	1,17	14
DINOPL	PLDINPL00011	47 937 000	8 916 282 000	5,733	9,13	12
JSW	PLJSW0000015	52 636 000	716 902 320	0,461	1,51	24
KGHM	PLKGHM000017	136 410 000	9 881 540 400	6,354	4,78	8
LOTOS	PLLOTOS00025	86 543 000	5 609 717 260	3,607	2,91	16
LPP	PLLPP0000011	1 306 000	7 444 200 000	4,787	1,43	19
MBANK	PLBRE0000012	12 997 000	2 830 746 600	1,820	0,42	24
ORANGEPL	PLTLKPL00017	647 357 000	4 285 503 340	2,756	1,16	13
PEKAO	PLPEKAO00016	176 379 000	9 619 710 660	6,185	5,27	9
PGE	PLPGER000010	796 776 000	3 561 588 720	2,290	2,88	18
PGNIG	PLPGNIG00014	1 624 608 000	6 072 784 704	3,905	1,56	12
PKNORLEN	PLPKN0000018	289 049 000	17 701 360 760	11,382	12,44	8
PKOBP	PLPKO0000016	857 593 000	18 807 014 490	12,093	10,49	9
PLAY	LU1642887738	114 151 000	3 696 209 380	2,377	1,47	16
PZU	PLPZU0000011	568 305 000	17 515 160 100	11,262	6,64	6
SANPL	PLBZ00000044	33 207 000	5 213 499 000	3,352	1,91	18
TAURONPE	PLTAURN00011	1 043 590 000	1 252 308 000	0,805	1,21	33"""
```

__Columns mean \:__

Instrument | ISIN code | Package | Package (PLN) | Share in portfolio (%) | Share in trading shares and PDAs per session (%) | Average spread per session

Split text into lines. Then divide each line by the tab character `\t` and build a numpy array (without headers) containing the following data. Assign the resulting array to the _result_ variable.

__Expected result:__
```
array([['ALIOR', 'PLALIOR00045', '88 860 000', '1 386 216 000', '0,891', '2,16', '14'],
       ['CCC', 'PLCCC0000016', '27 918 000', '1 292 603 400', '0,831', '5,28', '42'],
       ['CDPROJEKT', 'PLOPTTC00011', '67 348 000', '22 864 646 000', '14,702', '7,39', '7'],
       ['CYFRPLSAT', 'PLCFRPT00013', '275 301 000', '6 854 994 900', '4,408', '1,17', '14'],
       ['DINOPL', 'PLDINPL00011', '47 937 000', '8 916 282 000', '5,733', '9,13', '12'],
       ['JSW', 'PLJSW0000015', '52 636 000', '716 902 320', '0,461', '1,51', '24'],
       ['KGHM', 'PLKGHM000017', '136 410 000', '9 881 540 400', '6,354', '4,78', '8'],
       ['LOTOS', 'PLLOTOS00025', '86 543 000', '5 609 717 260', '3,607', '2,91', '16'],
       ['LPP', 'PLLPP0000011', '1 306 000', '7 444 200 000', '4,787', '1,43', '19'],
       ['MBANK', 'PLBRE0000012', '12 997 000', '2 830 746 600', '1,820', '0,42', '24'],
       ['ORANGEPL', 'PLTLKPL00017', '647 357 000', '4 285 503 340', '2,756', '1,16', '13'],
       ['PEKAO', 'PLPEKAO00016', '176 379 000', '9 619 710 660', '6,185', '5,27', '9'],
       ['PGE', 'PLPGER000010', '796 776 000', '3 561 588 720', '2,290', '2,88', '18'],
       ['PGNIG', 'PLPGNIG00014', '1 624 608 000', '6 072 784 704', '3,905', '1,56', '12'],
       ['PKNORLEN', 'PLPKN0000018', '289 049 000', '17 701 360 760', '11,382', '12,44', '8'],
       ['PKOBP', 'PLPKO0000016', '857 593 000', '18 807 014 490', '12,093', '10,49', '9'],
       ['PLAY', 'LU1642887738', '114 151 000', '3 696 209 380', '2,377', '1,47', '16'],
       ['PZU', 'PLPZU0000011', '568 305 000', '17 515 160 100', '11,262', '6,64', '6'],
       ['SANPL', 'PLBZ00000044', '33 207 000', '5 213 499 000', '3,352', '1,91', '18'],
       ['TAURONPE', 'PLTAURN00011', '1 043 590 000', '1 252 308 000', '0,805', '1,21', '33']],
      dtype='<U14')
```


In [39]:
text = """ALIOR	PLALIOR00045	88 860 000	1 386 216 000	0,891	2,16	14
CCC	PLCCC0000016	27 918 000	1 292 603 400	0,831	5,28	42
CDPROJEKT	PLOPTTC00011	67 348 000	22 864 646 000	14,702	7,39	7
CYFRPLSAT	PLCFRPT00013	275 301 000	6 854 994 900	4,408	1,17	14
DINOPL	PLDINPL00011	47 937 000	8 916 282 000	5,733	9,13	12
JSW	PLJSW0000015	52 636 000	716 902 320	0,461	1,51	24
KGHM	PLKGHM000017	136 410 000	9 881 540 400	6,354	4,78	8
LOTOS	PLLOTOS00025	86 543 000	5 609 717 260	3,607	2,91	16
LPP	PLLPP0000011	1 306 000	7 444 200 000	4,787	1,43	19
MBANK	PLBRE0000012	12 997 000	2 830 746 600	1,820	0,42	24
ORANGEPL	PLTLKPL00017	647 357 000	4 285 503 340	2,756	1,16	13
PEKAO	PLPEKAO00016	176 379 000	9 619 710 660	6,185	5,27	9
PGE	PLPGER000010	796 776 000	3 561 588 720	2,290	2,88	18
PGNIG	PLPGNIG00014	1 624 608 000	6 072 784 704	3,905	1,56	12
PKNORLEN	PLPKN0000018	289 049 000	17 701 360 760	11,382	12,44	8
PKOBP	PLPKO0000016	857 593 000	18 807 014 490	12,093	10,49	9
PLAY	LU1642887738	114 151 000	3 696 209 380	2,377	1,47	16
PZU	PLPZU0000011	568 305 000	17 515 160 100	11,262	6,64	6
SANPL	PLBZ00000044	33 207 000	5 213 499 000	3,352	1,91	18
TAURONPE	PLTAURN00011	1 043 590 000	1 252 308 000	0,805	1,21	33"""

# enter solution here

rows = text.split('\n')  
rows = [r.split('\t') for r in rows[1:]]  
result = np.array(rows)
print(result)

[['CCC' 'PLCCC0000016' '27 918 000' '1 292 603 400' '0,831' '5,28' '42']
 ['CDPROJEKT' 'PLOPTTC00011' '67 348 000' '22 864 646 000' '14,702'
  '7,39' '7']
 ['CYFRPLSAT' 'PLCFRPT00013' '275 301 000' '6 854 994 900' '4,408' '1,17'
  '14']
 ['DINOPL' 'PLDINPL00011' '47 937 000' '8 916 282 000' '5,733' '9,13'
  '12']
 ['JSW' 'PLJSW0000015' '52 636 000' '716 902 320' '0,461' '1,51' '24']
 ['KGHM' 'PLKGHM000017' '136 410 000' '9 881 540 400' '6,354' '4,78' '8']
 ['LOTOS' 'PLLOTOS00025' '86 543 000' '5 609 717 260' '3,607' '2,91' '16']
 ['LPP' 'PLLPP0000011' '1 306 000' '7 444 200 000' '4,787' '1,43' '19']
 ['MBANK' 'PLBRE0000012' '12 997 000' '2 830 746 600' '1,820' '0,42' '24']
 ['ORANGEPL' 'PLTLKPL00017' '647 357 000' '4 285 503 340' '2,756' '1,16'
  '13']
 ['PEKAO' 'PLPEKAO00016' '176 379 000' '9 619 710 660' '6,185' '5,27' '9']
 ['PGE' 'PLPGER000010' '796 776 000' '3 561 588 720' '2,290' '2,88' '18']
 ['PGNIG' 'PLPGNIG00014' '1 624 608 000' '6 072 784 704' '3,905' '1,56'
  '12']
 ['PKNOR

### <a name='8'></a> Exercise 88
From the _result_ array from the previous exercise, remove all spaces in the text and replace all commas with periods.

In [52]:
# enter solution here

text = """ALIOR	PLALIOR00045	88 860 000	1 386 216 000	0,891	2,16	14
CCC	PLCCC0000016	27 918 000	1 292 603 400	0,831	5,28	42
CDPROJEKT	PLOPTTC00011	67 348 000	22 864 646 000	14,702	7,39	7
CYFRPLSAT	PLCFRPT00013	275 301 000	6 854 994 900	4,408	1,17	14
DINOPL	PLDINPL00011	47 937 000	8 916 282 000	5,733	9,13	12
JSW	PLJSW0000015	52 636 000	716 902 320	0,461	1,51	24
KGHM	PLKGHM000017	136 410 000	9 881 540 400	6,354	4,78	8
LOTOS	PLLOTOS00025	86 543 000	5 609 717 260	3,607	2,91	16
LPP	PLLPP0000011	1 306 000	7 444 200 000	4,787	1,43	19
MBANK	PLBRE0000012	12 997 000	2 830 746 600	1,820	0,42	24
ORANGEPL	PLTLKPL00017	647 357 000	4 285 503 340	2,756	1,16	13
PEKAO	PLPEKAO00016	176 379 000	9 619 710 660	6,185	5,27	9
PGE	PLPGER000010	796 776 000	3 561 588 720	2,290	2,88	18
PGNIG	PLPGNIG00014	1 624 608 000	6 072 784 704	3,905	1,56	12
PKNORLEN	PLPKN0000018	289 049 000	17 701 360 760	11,382	12,44	8
PKOBP	PLPKO0000016	857 593 000	18 807 014 490	12,093	10,49	9
PLAY	LU1642887738	114 151 000	3 696 209 380	2,377	1,47	16
PZU	PLPZU0000011	568 305 000	17 515 160 100	11,262	6,64	6
SANPL	PLBZ00000044	33 207 000	5 213 499 000	3,352	1,91	18
TAURONPE	PLTAURN00011	1 043 590 000	1 252 308 000	0,805	1,21	33"""

# enter solution here

result = np.char.replace(result, ' ', '') 
result = np.char.replace(result, ',', '.')

print(result)

[['CCC' 'PLCCC0000016' '27918000' '1292603400' '0.831' '5.28' '42']
 ['CDPROJEKT' 'PLOPTTC00011' '67348000' '22864646000' '14.702' '7.39' '7']
 ['CYFRPLSAT' 'PLCFRPT00013' '275301000' '6854994900' '4.408' '1.17' '14']
 ['DINOPL' 'PLDINPL00011' '47937000' '8916282000' '5.733' '9.13' '12']
 ['JSW' 'PLJSW0000015' '52636000' '716902320' '0.461' '1.51' '24']
 ['KGHM' 'PLKGHM000017' '136410000' '9881540400' '6.354' '4.78' '8']
 ['LOTOS' 'PLLOTOS00025' '86543000' '5609717260' '3.607' '2.91' '16']
 ['LPP' 'PLLPP0000011' '1306000' '7444200000' '4.787' '1.43' '19']
 ['MBANK' 'PLBRE0000012' '12997000' '2830746600' '1.820' '0.42' '24']
 ['ORANGEPL' 'PLTLKPL00017' '647357000' '4285503340' '2.756' '1.16' '13']
 ['PEKAO' 'PLPEKAO00016' '176379000' '9619710660' '6.185' '5.27' '9']
 ['PGE' 'PLPGER000010' '796776000' '3561588720' '2.290' '2.88' '18']
 ['PGNIG' 'PLPGNIG00014' '1624608000' '6072784704' '3.905' '1.56' '12']
 ['PKNORLEN' 'PLPKN0000018' '289049000' '17701360760' '11.382' '12.44'
  '8']
 ['PK

Then extract column 'Share in portfolio (%)' convert its type to _float_ and calculate the sum for this column. Check if it's 100%.

In [50]:
# enter solution here
share = result[:,4].astype(float)
print(f"Sum of Share in portfolio (%): {share.sum():.2f}")


Sum of Share in portfolio (%): 99.11


### <a name='9'></a> Exercise 89
From the _result_ array, extract all the rows with the company name beginning with the letter P and assign it to the variable _stocks_startswith_P_.

__Expected result:__

```
array([['PEKAO', 'PLPEKAO00016', '176379000', '9619710660', '6.185', '5.27', '9'],
       ['PGE', 'PLPGER000010', '796776000', '3561588720', '2.290', '2.88', '18'],
       ['PGNIG', 'PLPGNIG00014', '1624608000', '6072784704', '3.905', '1.56', '12'],
       ['PKNORLEN', 'PLPKN0000018', '289049000', '17701360760', '11.382', '12.44', '8'],
       ['PKOBP', 'PLPKO0000016', '857593000', '18807014490', '12.093', '10.49', '9'],
       ['PLAY', 'LU1642887738', '114151000', '3696209380', '2.377', '1.47', '16'],
       ['PZU', 'PLPZU0000011', '568305000', '17515160100', '11.262', '6.64', '6']], dtype='<U12')
```

In [48]:

# enter solution here
startswith_P = result[np.char.startswith(result[:,0], 'P')]
print(startswith_P)  



[['PEKAO' 'PLPEKAO00016' '176379000' '9619710660' '6.185' '5.27' '9']
 ['PGE' 'PLPGER000010' '796776000' '3561588720' '2.290' '2.88' '18']
 ['PGNIG' 'PLPGNIG00014' '1624608000' '6072784704' '3.905' '1.56' '12']
 ['PKNORLEN' 'PLPKN0000018' '289049000' '17701360760' '11.382' '12.44'
  '8']
 ['PKOBP' 'PLPKO0000016' '857593000' '18807014490' '12.093' '10.49' '9']
 ['PLAY' 'LU1642887738' '114151000' '3696209380' '2.377' '1.47' '16']
 ['PZU' 'PLPZU0000011' '568305000' '17515160100' '11.262' '6.64' '6']]


### <a name='10'></a> Exercise 90
Using the variable _stocks_startswith_P_, calculate the total share of companies whose name begins with the letter P. Round the result to two decimal places.

In [49]:
# enter solution here



sum_p_stocks = stocks_startswith_P[:,4].astype(float).sum()
print(f"Total share of P stocks: {sum_p_stocks:.2f}%")

Total share of P stocks: 49.49%


### <a name='1'></a> Exercise 91
The following string _wig_games_raw_ is provided containing data on the WIG.GAMES sector index:

```
wig_games_raw = """Profile	Time	Course	Change	Change%	Ref.	Open	Low	High	Volume	Turn	Share
11B (11BIT)	17 kwi 17:01	391.00	+8.00	(+2.09%)	383.00	383.50	383.00	394.00	12 784	4 994 874	19.034%
CDR (CDPROJEKT)	17 kwi 17:01	339.50	+5.30	(+1.59%)	334.20	338.30	337.00	344.20	233 059	79 245 368	39.618%
CIG (CIGAMES)	17 kwi 17:03	0.742	-0.012	(-1.59%)	0.754	0.772	0.730	0.772	1 311 078	971 459	1.855%
PLW (PLAYWAY)	17 kwi 17:03	387.50	+18.00	(+4.87%)	369.50	374.00	373.00	388.00	33 206	12 661 786	10.638%
TEN (TSGAMES)	17 kwi 17:02	349.50	+22.50	(+6.88%)	327.00	332.00	330.00	353.50	39 793	13 697 060	28.855%"""
```
Build a numpy array from this data and name it _wig_games_.

__Expected result:__
```
array([['Profil', 'Czas', 'Kurs', 'Zmiana', 'Zmiana%', 'Odn.', 'Otw.', 'Min.', 'Max.', 'Wolumen', 'Obrót', 'Udział'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '+8.00', '(+2.09%)', '383.00', '383.50', '383.00', '394.00', '12784', '4994874', '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '+5.30', '(+1.59%)', '334.20', '338.30', '337.00', '344.20', '233059', '79245368', '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '-0.012', '(-1.59%)', '0.754', '0.772', '0.730', '0.772', '1311078', '971459', '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '+18.00', '(+4.87%)', '369.50', '374.00', '373.00', '388.00', '33206', '12661786', '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '+22.50', '(+6.88%)', '327.00', '332.00', '330.00', '353.50', '39793', '13697060', '28.855%']], dtype='<U14')
```


In [56]:
wig_games_raw = """Profile	Time	Course	Change	Change%	Ref.	Open	Low	High	Volume	Turn	Share
11B (11BIT)	17 kwi 17:01	391.00	+8.00	(+2.09%)	383.00	383.50	383.00	394.00	12 784	4 994 874	19.034%
CDR (CDPROJEKT)	17 kwi 17:01	339.50	+5.30	(+1.59%)	334.20	338.30	337.00	344.20	233 059	79 245 368	39.618%
CIG (CIGAMES)	17 kwi 17:03	0.742	-0.012	(-1.59%)	0.754	0.772	0.730	0.772	1 311 078	971 459	1.855%
PLW (PLAYWAY)	17 kwi 17:03	387.50	+18.00	(+4.87%)	369.50	374.00	373.00	388.00	33 206	12 661 786	10.638%
TEN (TSGAMES)	17 kwi 17:02	349.50	+22.50	(+6.88%)	327.00	332.00	330.00	353.50	39 793	13 697 060	28.855%"""

# enter solution here
rows = wig_games_raw.split('\n')
rows = [r.split('\t') for r in rows]  
wig_games = np.array(rows)
print(wig_games)



[['Profile' 'Time' 'Course' 'Change' 'Change%' 'Ref.' 'Open' 'Low' 'High'
  'Volume' 'Turn' 'Share']
 ['11B (11BIT)' '17 kwi 17:01' '391.00' '+8.00' '(+2.09%)' '383.00'
  '383.50' '383.00' '394.00' '12 784' '4 994 874' '19.034%']
 ['CDR (CDPROJEKT)' '17 kwi 17:01' '339.50' '+5.30' '(+1.59%)' '334.20'
  '338.30' '337.00' '344.20' '233 059' '79 245 368' '39.618%']
 ['CIG (CIGAMES)' '17 kwi 17:03' '0.742' '-0.012' '(-1.59%)' '0.754'
  '0.772' '0.730' '0.772' '1 311 078' '971 459' '1.855%']
 ['PLW (PLAYWAY)' '17 kwi 17:03' '387.50' '+18.00' '(+4.87%)' '369.50'
  '374.00' '373.00' '388.00' '33 206' '12 661 786' '10.638%']
 ['TEN (TSGAMES)' '17 kwi 17:02' '349.50' '+22.50' '(+6.88%)' '327.00'
  '332.00' '330.00' '353.50' '39 793' '13 697 060' '28.855%']]


### <a name='2'></a> Exercise 92
Remove the columns from the _wig_games_ array from the previous exercise:
* Change
* Change%
* Ref.
* Volume

__Expected result:__
```
array([['Profile', 'Time', 'Course', 'Open', 'Low', 'High', 'Turn', 'Share'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '383.50', '383.00', '394.00', '4994874', '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '338.30', '337.00', '344.20', '79245368', '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '0.772', '0.730', '0.772', '971459', '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '374.00', '373.00', '388.00', '12661786', '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '332.00', '330.00', '353.50', '13697060', '28.855%']], dtype='<U14')
```


In [65]:
# enter solution here
wig_games = np.delete(wig_games, [2,3,5,8], 1) 
print(wig_games)



IndexError: index 8 is out of bounds for axis 0 with size 8

### <a name='3'></a> Exercise 93
Save the array _wig_games_ from the previous exercise to the _wig_games.csv_ file.

In [67]:
# enter solution here

C = np.savetxt('wig_games.csv', wig_games, fmt='%s', delimiter=',')


None


Run the cell below to check.

'head' is not recognized as an internal or external command,
operable program or batch file.


### <a name='4'></a> Exercise 94
Load the contents of the _wig_games.csv_ file into the _wig_games_new_ variable.

In [68]:
# enter solution here
wig_games_new = np.loadtxt('wig_games.csv', dtype=str, delimiter=',') 



### <a name='5'></a> Exercise 95
The following string _playway_raw_ is provided containing Playway's March 2020 listings:

```
playway_raw = """Date,Open,High,Low,Close,Volume
2020-03-02,305,324.5,283.5,310,64081
2020-03-03,325.5,340.5,320,340.5,55496
2020-03-04,324,340.5,315,330,36152
2020-03-05,344,344,310,315,35992
2020-03-06,306.5,307,291,305,32539
2020-03-09,274,291,250,258,79402
2020-03-10,278,284.5,256,264,35700
2020-03-11,270,270,238.5,245,60445
2020-03-12,218,228,196,197,94031
2020-03-13,210,229,198.8,211,100412
2020-03-16,205,248,197.8,240.5,50659
2020-03-17,245,269,232.5,264,99480
2020-03-18,264,280,251,270,70136
2020-03-19,267,280,267,279.5,30732
2020-03-20,297.5,307,280,280.5,43426
2020-03-23,274,289,258,285,37098
2020-03-24,305,309,296.5,309,31939
2020-03-25,313,330,295,304,46724
2020-03-26,300,309,295.5,300,27213
2020-03-27,302,306.5,290,296,13466
2020-03-30,299,300,287,300,10316
2020-03-31,302.5,309,302,306.5,15698"""
```

Create an array named _playway_ and assign the following data to it.

In [74]:
playway_raw = """Date,Open,High,Low,Close,Volume
2020-03-02,305,324.5,283.5,310,64081
2020-03-03,325.5,340.5,320,340.5,55496
2020-03-04,324,340.5,315,330,36152
2020-03-05,344,344,310,315,35992
2020-03-06,306.5,307,291,305,32539
2020-03-09,274,291,250,258,79402
2020-03-10,278,284.5,256,264,35700
2020-03-11,270,270,238.5,245,60445
2020-03-12,218,228,196,197,94031
2020-03-13,210,229,198.8,211,100412
2020-03-16,205,248,197.8,240.5,50659
2020-03-17,245,269,232.5,264,99480
2020-03-18,264,280,251,270,70136
2020-03-19,267,280,267,279.5,30732
2020-03-20,297.5,307,280,280.5,43426
2020-03-23,274,289,258,285,37098
2020-03-24,305,309,296.5,309,31939
2020-03-25,313,330,295,304,46724
2020-03-26,300,309,295.5,300,27213
2020-03-27,302,306.5,290,296,13466
2020-03-30,299,300,287,300,10316
2020-03-31,302.5,309,302,306.5,15698"""

# enter solution here
playway_rows = playway_raw.strip().split('\n')
playway = [row.split(',')[1:] for row in playway_rows[1:]]
playway = np.array(playway)
playway

array([['305', '324.5', '283.5', '310', '64081'],
       ['325.5', '340.5', '320', '340.5', '55496'],
       ['324', '340.5', '315', '330', '36152'],
       ['344', '344', '310', '315', '35992'],
       ['306.5', '307', '291', '305', '32539'],
       ['274', '291', '250', '258', '79402'],
       ['278', '284.5', '256', '264', '35700'],
       ['270', '270', '238.5', '245', '60445'],
       ['218', '228', '196', '197', '94031'],
       ['210', '229', '198.8', '211', '100412'],
       ['205', '248', '197.8', '240.5', '50659'],
       ['245', '269', '232.5', '264', '99480'],
       ['264', '280', '251', '270', '70136'],
       ['267', '280', '267', '279.5', '30732'],
       ['297.5', '307', '280', '280.5', '43426'],
       ['274', '289', '258', '285', '37098'],
       ['305', '309', '296.5', '309', '31939'],
       ['313', '330', '295', '304', '46724'],
       ['300', '309', '295.5', '300', '27213'],
       ['302', '306.5', '290', '296', '13466'],
       ['299', '300', '287', '300', '1031

Delete the column named 'Date'. Assign only column values without headers to the _playway_values_ variable. Convert the array to the _float_ data type.

__Expected result:__
```
array([[   305. ,    324.5,    283.5,    310. ,  64081. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ],
       [   313. ,    330. ,    295. ,    304. ,  46724. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ],
       [   302. ,    306.5,    290. ,    296. ,  13466. ],
       [   299. ,    300. ,    287. ,    300. ,  10316. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ]])
```

In [ ]:
# enter solution here

### <a name='6'></a> Exercise 96
For the _playway_values_ array from the previous exercise, calculate the average value for each column. Round the result to two decimal places.

In [ ]:
# enter solution here

For the _playway_values_ array from the previous exercise, calculate the minimum value for each column. Round the result to two decimal places.

In [ ]:
# enter solution here

For the _playway_values_ array from the previous exercise, calculate the maximum value for each column. Round the result to two decimal places.

In [ ]:
# enter solution here

Calculate the difference between the maximum and minimum value for each column.

In [ ]:
# enter solution here

### <a name='7'></a> Exercise 97
Using the _playway_values_ array, calculate the new column: the difference between the highest and lowest price.

Steps:
1. assign the calculated difference to the _max_min_diff_ variable
2. add the calculated column (variable _max_min_diff_) to the array _playway_values_ at the end.

__Expected result:__
```
array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5],
       [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5],
       [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ]])
```

In [ ]:
# enter solution here

### <a name='8'></a> Exercise 98
Extract rows from the array _playway_values_ where closing price is grater than 300.00.

In [ ]:
# enter solution here

### <a name='9'></a> Exercise 99
From the array _playway_values_ extract the first 10 rows with the highest volume value sorted in descending order.

In [ ]:
# enter solution here

### <a name='10'></a> Exercise 100
Add to the _playway_values_ array column that will return 1 in case the closing price is higher than the opening price and 0 opposite.

__Expected result:__
```
array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ,      1. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5,      1. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5,      1. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ,      0. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ,      0. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ,      0. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5,      0. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5,      0. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ,      0. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2,      1. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2,      1. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5,      1. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ,      1. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ,      1. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ,      0. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ,      1. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5,      1. ],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ,      0. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5,      0. ],
       [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5,      0. ],
       [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ,      1. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ,      1. ]])
```

In [ ]:
# enter solution here